name = "ubiquity-os-daemon-spec-rewriter"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
[env.dev]
[env.prod]

[observability]
enabled = true

[version_metadata]
binding = "CLOUDFLARE_VERSION_METADATA"